### ISSUE TITLE
java.sql.SQLSyntaxErrorException on my-db-name.Migration

### ISSUE THREAD

**Issue by maxdarque** [maxdarque/prisma-docker#2]
When I run `docker-compose up` I get the following error where `my-db-name` is DB_NAME from .env. Or `SQL_INTERNAL_DATABASE` if you will from the environment variables in docker-compose.yml
```
Recreating prisma ... done
Attaching to prisma
prisma    | Listening for transport dt_socket at address: 8000
prisma    | Obtaining exclusive agent lock...
prisma    | Obtaining exclusive agent lock... Successful.
prisma    | Fatal error during deployment worker initialization: java.sql.SQLSyntaxErrorException: (conn=2507) Table 'my-db-name.Migration' doesn't exist
prisma exited with code 255
```

**Comment by maxdarque** [comment]
It might be linked to 
-[Migrator.scala](https://github.com/graphcool/prisma/blob/7b3da2706b9c80a4f17bfa2e571c11618d58f735/server/deploy/src/main/scala/com/prisma/deploy/migration/migrator/Migrator.scala)
-[AsyncMigrator.scala](https://github.com/graphcool/prisma/blob/7b3da2706b9c80a4f17bfa2e571c11618d58f735/server/deploy/src/main/scala/com/prisma/deploy/migration/migrator/AsyncMigrator.scala)
-[MigrationApplier.scala](https://github.com/graphcool/prisma/blob/7b3da2706b9c80a4f17bfa2e571c11618d58f735/server/deploy/src/main/scala/com/prisma/deploy/migration/migrator/MigrationApplier.scala)

**Comment by maxdarque** [comment]
If I leave `SQL_INTERNAL_DATABASE` blank in the docker-compose.yml file I get the following error

```
meep:prisma-docker Max$ docker-compose up
Creating network "prismadocker_default" with the default driver
Creating prisma ... done
Attaching to prisma
prisma    | Listening for transport dt_socket at address: 8000
prisma    | Obtaining exclusive agent lock...
prisma    | Initializing workers...
prisma    | Successfully started 1 workers.
prisma    | Server running on :4466
prisma    | Version is up to date.
prisma    | Fatal error during deployment worker initialization: java.sql.SQLTransientConnectionException: internal - Connection is not available, request timed out after 5000ms.
prisma exited with code 255
```

**Comment by akoenig** [comment]
@maxdarque `Table 'my-db-name.Migration' doesn't exist` happens when you set `SQL_INTERNAL_DATABASE` to something else than `graphcool`. This is the database which is used by Prisma internally.

The other option would be to create the database `my-db-name` before starting the Prisma container.

**Comment by maxdarque** [comment]
This just might be it 👍 

I set SQL_INTERNAL_DATABASE to graphcool and it looks like the container is up and running.

I'm going to test it
